---
- name: Update and Upgrade apt packages
  sudo: yes
  apt: >
    upgrade=yes
    update_cache=yes
    cache_valid_time=3600
  tags:
    - update

- name: Install required packages
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
       - htop
       - vim
       - git
       - build-essential
       - libssl-dev
       - nodejs
       - libpq-dev # for postgresql
  tags:
    - required-packages
