---
- name: Install RVM
  include: 'rvm.yml'
  become: yes
  become_user: '{{ rvm1_user }}'
  tags:
    - rvm

- name: Install Ruby and Gems
  include: 'rubies.yml'
  become: yes
  become_user: '{{ rvm1_user }}'
  tags:
    - rvm-rubies
